In [8]:
from astropy.io import fits
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import aplpy
from astropy import units as u
from astropy.wcs import WCS
from astropy.coordinates import SkyCoord
from astroquery.gaia import Gaia
import pandas as pd
pd.set_option('display.max_columns', 100)
import seaborn as sns
sns.set(font="times",font_scale=1.7,style="ticks")
import matplotlib as mpl
mpl.rc('text', usetex=True)
from zero_point import zpt
zpt.load_tables()
%matplotlib inline
%config InlineBackend.figure_formats = {'png', 'retina'}

In [9]:
search30 = pd.read_csv("../files/cluster_search.csv")

In [10]:
for name in search30.Cluster:
    match = []
    Name = name.replace(" ","")
    stars_c = pd.read_csv("../match/"+str(Name)+".csv")
    stars_q = pd.read_csv("../query/"+str(Name)+".csv")
    for i,row in stars_c.iterrows():
        ra  = row["_RA.icrs"]
        dec = row["_DE.icrs"]
        ra_q  = stars_q.ra
        dec_q = stars_q.dec
        diff  = np.sqrt((ra_q-ra)**2+(dec_q-dec)**2)
        min_index = np.argmin(diff)
        mt = stars_q.iloc[min_index]
        array = np.append(mt.values,np.min(diff))
        match.append(array)
    print(name,i)
    columns = stars_q.columns.values
    columns = np.append(columns,"diff_min")
    match = pd.DataFrame(data=match,columns=columns)
    match.to_csv("../match_final/"+str(Name)+".csv",index=False)

Collinder_69      221
IC_2714           833
IC_4651           757
Melotte_22        213
Melotte_25        6
NGC_1647          458
NGC_2099          1580
NGC_2112          685
NGC_2168          1041
NGC_2287          504
NGC_2323          652
NGC_2360          678
NGC_2437          1661
NGC_2447          673
NGC_2477          1712
NGC_2516          369
NGC_2632          208
NGC_2682          597
NGC_3114          755
NGC_3532          939
NGC_4755          588
NGC_5822          446
NGC_6067          841
NGC_6124          868
NGC_6134          766
NGC_6192          513
NGC_6231          526
NGC_6405          499
NGC_6475          301
UPK_640           110

In [11]:
match

,source_id,ra,dec,l,b,phot_g_mean_mag,bp_rp,parallax,parallax_error,priam_flags,flame_flags,a_g_val,e_bp_min_rp_val,teff_val,radius_val,radius_percentile_lower,radius_percentile_upper,original_ext_source_id,j_m,h_m,ks_m,diff_min
0,5969195751920335360,250.500565,-40.049481,343.342795,4.084704,11.437051,1.251085,5.689129,0.048314,100001.0,200111.0,1.0450,0.5150,4825.2500,1.201777,1.115423,1.248184,16420014-4002577,9.812,9.312,9.159,0.000113
1,5969200871522420992,250.599926,-40.058329,343.386183,4.021542,9.356070,1.008392,5.501638,0.086820,100001.0,200111.0,NaN,NaN,5094.0000,2.819362,2.625815,2.864469,16422399-4003296,8.047,7.614,7.464,0.000115
2,5969201489997778176,250.555087,-40.041711,343.376158,4.058342,15.079073,3.127730,5.715158,0.079497,100002.0,200111.0,1.2507,0.7137,3694.1800,0.509106,0.413306,0.599790,16421323-4002298,11.805,11.211,10.921,0.000114
3,5969201623077411840,250.501384,-40.046007,343.345833,4.086515,12.827961,1.702975,5.582314,0.053947,100001.0,200111.0,NaN,NaN,4207.8926,0.959812,0.893120,1.018644,16420034-4002452,10.779,10.112,9.937,0.000110
4,5969226881848068096,250.773048,-39.884944,343.604629,4.035001,15.299573,3.034021,5.915761,0.098246,100002.0,NaN,0.8980,0.5330,4139.7100,NaN,NaN,NaN,16430554-3953054,12.131,11.520,11.270,0.000115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,6017529217893388032,249.815478,-38.954110,343.818615,5.204675,15.391121,3.163429,5.696934,0.084502,100001.0,NaN,1.0243,0.5635,3564.9531,NaN,NaN,NaN,16391572-3857143,12.109,11.541,11.246,0.000113
107,6017529733289470080,249.748892,-38.952601,343.785289,5.244451,17.894493,3.580282,5.255934,0.218323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16385974-3857090,14.255,13.630,13.318,0.000110
108,6017548867341963264,249.972952,-38.972627,343.886031,5.100621,19.099413,2.380999,0.832005,0.474218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16395351-3858211,16.177,15.553,14.379,0.002150
109,6017548867341963264,249.972952,-38.972627,343.886031,5.100621,19.099413,2.380999,0.832005,0.474218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16395351-3858211,16.177,15.553,14.379,0.002587
110,6017549180911020288,249.916625,-38.973139,343.856570,5.133131,14.532433,2.513749,5.672363,0.064914,100002.0,200111.0,NaN,NaN,3504.9650,0.785963,0.651990,0.871249,16394000-3858228,11.693,10.977,10.751,0.000111